[package]
name = "phantom_ci"
version = "0.1.1"
edition = "2021"
description = "Secure Headless Self-Hosted Runner"
keywords = ["self-hosted", "git", "scm", "cicd"]
authors = ["james@koonts.net"]

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
whoami = "2.0.0-pre.0"
config = "0.14.1"
rand = "0.9.0-beta.0"
chrono = "0.4.38"