# Example workflow for branch-specific file at $REPO_ROOT/workflow/<branch>.toml

[0]
run = "pwd"

[1]
run = "echo 'Running tests' && cargo test --all --quiet"

[2]
run = "echo 'Building release' && cargo build --release --quiet"

[3]
run = "echo 'Formatting check' && cargo fmt -- --check"

# If you need shell features like && or pipes, explicitly call bash -lc
[4]
run = "bash -lc 'echo \"Current branch: $(git rev-parse --abbrev-ref HEAD)\"'"